# -*- coding: utf-8 -*-
"""creditoxinadimplencia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6GfVAnSyCDT_YK4E4YuZ0Z_9D1ZyKAp

# **Análise: taxa de inadimplência MEI**

Importação de bibliotecas
"""

import json
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""Carregando tabelas:


*   Taxa de Inadimplência
*   Saldo de Crédito


"""

inad = pd.read_json('inadimplencia.json')
cred = pd.read_json('credito.json')

display(inad)
display(cred)

inad.describe()

cred.describe()

"""Unindo as duas tabelas uma ao lado da outra"""

tabela = pd.merge(inad, cred, on='data')
display(tabela)

"""Alterando nome das colunas"""

tabela.rename(columns = {'data': 'data', 'valor_x': 'inadimplencia', 'valor_y':'credito'}, inplace=True)
tabela

"""Gráficos"""

import scipy.stats as stats
import statsmodels

"""Análise de Normalidade"""

stats.probplot(tabela['inadimplencia'], dist='norm', plot=plt)
plt.title('Análise Normalidade - Inadimplência')
plt.show()

stats.probplot(tabela['credito'], dist='norm', plot=plt)
plt.title('Análise Normalidade - Crédito')
plt.show()

"""Correlação"""

correlation = tabela.corr()
plot = sns.heatmap(correlation, annot = True, fmt='.1f', linewidths=.6)
plot;

plt.scatter(tabela.inadimplencia, tabela.credito)
plt.title('Correlação Linear')
plt.xlabel('Inadimplência')
plt.ylabel('Crédito')
plt.grid(False)
plt.show()

sns.pairplot(tabela);

"""Histrograma"""

sns.histplot(tabela, x='inadimplencia', bins=20, color='blue', kde=True, stat='probability',);

sns.histplot(tabela, x='credito', bins=20, color='blue', kde=True, stat='probability',);

"""Outliers"""

sns.boxplot(x=tabela['inadimplencia'])

plt.title('Distribuição da Taxa de Inadimplência')
plt.ylabel('Crédito - R$')
plt.show()

sns.boxplot(x=tabela['credito'])

plt.title('Distribuição de Crédito')
plt.ylabel('Taxa de Inadimplência')
plt.show()